2024-05-13 07:49:24,464 CallHome: calling aide.submit_statistics(url=None, tool_id=52380, metadata={'pid': '000000', 'customer': '', 'cxta_version': '24.5', 'execution_time': 4.9, 'potential_savings': 0.5, 'report_savings': True, 'suite_name': 'Dnac Ui', 'run_from': 'cli', 'devices_os': {}, 'cxtalibs_used': defaultdict(<class 'int'>, {'Browser': 2})}, client_id=Dnac Ui@0b0521eda1344f1b2275575a3bc8fd4cd97fd0c7, version_check=False)
2024-05-13 07:49:24,465 The CX Project ID will be collected for AIDE reporting purposes only.
2024-05-13 07:49:24,465 JSON data to be sent: '[{"aide_uid": "52380", "timestamp": "2024-05-13 07:49:24.465082", "client_id": "5ad15c38552200a8893b0465d0729df6ab33a350d9bd9d7228b99109ea207bab3477d5f42c3720c9409aa292718719efc34dc48b1ee502dd4ce9ef5587b68f30", "cli": "robot", "language": "python", "language_version": "3.10.12", "pid": "000000", "metadata": {"pid": "000000", "customer": "", "cxta_version": "24.5", "execution_time": 4.9, "potential_savings": 0.5, "report_savings": true, "suite_name": "Dnac Ui", "run_from": "cli", "devices_os": {}, "cxtalibs_used": {"Browser": 2}}, "os": "Linux", "agent_name": "aide-python-agent", "agent_version": "4.1.0", "os_version": "6.6.22-linuxkit"}]'
2024-05-13 07:49:24,753 Hostname 'api-auc.cisco.com' is not reachable. Error: [Errno -2] Name or service not known
2024-05-13 07:49:24,754 aide.submit_statistics() returned: False
2024-05-13 07:51:49,918 CallHome: calling aide.submit_statistics(url=None, tool_id=52380, metadata={'pid': '000000', 'customer': '', 'cxta_version': '24.5', 'execution_time': 3.1, 'potential_savings': 0.5, 'report_savings': True, 'suite_name': 'Dnac Ui', 'run_from': 'cli', 'devices_os': {}, 'cxtalibs_used': defaultdict(<class 'int'>, {'Browser': 2})}, client_id=Dnac Ui@0b0521eda1344f1b2275575a3bc8fd4cd97fd0c7, version_check=False)
2024-05-13 07:51:49,919 The CX Project ID will be collected for AIDE reporting purposes only.
2024-05-13 07:51:49,919 JSON data to be sent: '[{"aide_uid": "52380", "timestamp": "2024-05-13 07:51:49.919170", "client_id": "5ad15c38552200a8893b0465d0729df6ab33a350d9bd9d7228b99109ea207bab3477d5f42c3720c9409aa292718719efc34dc48b1ee502dd4ce9ef5587b68f30", "cli": "robot", "language": "python", "language_version": "3.10.12", "pid": "000000", "metadata": {"pid": "000000", "customer": "", "cxta_version": "24.5", "execution_time": 3.1, "potential_savings": 0.5, "report_savings": true, "suite_name": "Dnac Ui", "run_from": "cli", "devices_os": {}, "cxtalibs_used": {"Browser": 2}}, "os": "Linux", "agent_name": "aide-python-agent", "agent_version": "4.1.0", "os_version": "6.6.22-linuxkit"}]'
2024-05-13 07:51:49,922 Hostname 'api-auc.cisco.com' is not reachable. Error: [Errno -2] Name or service not known
2024-05-13 07:51:49,923 aide.submit_statistics() returned: False
2024-05-13 08:09:40,694 CallHome: calling aide.submit_statistics(url=None, tool_id=52380, metadata={'pid': '000000', 'customer': '', 'cxta_version': '24.5', 'execution_time': 5.0, 'potential_savings': 0.5, 'report_savings': True, 'suite_name': 'Dnac Ui', 'run_from': 'cli', 'devices_os': {}, 'cxtalibs_used': defaultdict(<class 'int'>, {'Browser': 2})}, client_id=Dnac Ui@0b0521eda1344f1b2275575a3bc8fd4cd97fd0c7, version_check=False)
2024-05-13 08:09:40,696 The CX Project ID will be collected for AIDE reporting purposes only.
2024-05-13 08:09:40,696 JSON data to be sent: '[{"aide_uid": "52380", "timestamp": "2024-05-13 08:09:40.695955", "client_id": "5ad15c38552200a8893b0465d0729df6ab33a350d9bd9d7228b99109ea207bab3477d5f42c3720c9409aa292718719efc34dc48b1ee502dd4ce9ef5587b68f30", "cli": "robot", "language": "python", "language_version": "3.10.12", "pid": "000000", "metadata": {"pid": "000000", "customer": "", "cxta_version": "24.5", "execution_time": 5.0, "potential_savings": 0.5, "report_savings": true, "suite_name": "Dnac Ui", "run_from": "cli", "devices_os": {}, "cxtalibs_used": {"Browser": 2}}, "os": "Linux", "agent_name": "aide-python-agent", "agent_version": "4.1.0", "os_version": "6.6.22-linuxkit"}]'
2024-05-13 08:09:40,699 Hostname 'api-auc.cisco.com' is not reachable. Error: [Errno -2] Name or service not known
2024-05-13 08:09:40,700 aide.submit_statistics() returned: False
